In [2]:
import numpy as np

In [2]:
np.__version__

'1.20.1'

In [3]:
np.show_config

<function numpy.__config__.show()>

In [5]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
x.size

10

In [7]:
x.itemsize

8

In [8]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [9]:
y = np.zeros(10)
y[4] = 1
y

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [10]:
z = np.arange(10, 50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [11]:
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [12]:
mat = np.arange(0, 9).reshape(3, 3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
arr = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

In [14]:
mat1 = np.identity(3)
mat1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
mat2 = np.random.random((3, 3, 3))
mat2

array([[[0.34394857, 0.52165694, 0.0715193 ],
        [0.22417318, 0.67883534, 0.03151554],
        [0.1891087 , 0.50260637, 0.38647598]],

       [[0.0703186 , 0.06200325, 0.92845549],
        [0.52517724, 0.9594809 , 0.26300165],
        [0.82868491, 0.26442051, 0.3723887 ]],

       [[0.19895539, 0.39303052, 0.02541926],
        [0.74919724, 0.54472319, 0.09585787],
        [0.82650618, 0.24123933, 0.4721412 ]]])

In [17]:
arr1 = np.random.random((10, 10))
arr1

array([[0.81827885, 0.84339337, 0.95361737, 0.49545244, 0.7906238 ,
        0.14061649, 0.34420735, 0.79047638, 0.16306503, 0.74072838],
       [0.40098291, 0.92898205, 0.29575954, 0.28595352, 0.37643507,
        0.36368403, 0.79896575, 0.71880147, 0.2437965 , 0.08526869],
       [0.39760024, 0.71754522, 0.55610951, 0.13245376, 0.89528756,
        0.81933548, 0.65892328, 0.50352664, 0.03595548, 0.74166102],
       [0.34433194, 0.88467309, 0.35503267, 0.54101305, 0.18358401,
        0.94734503, 0.229897  , 0.49581591, 0.40672978, 0.3807704 ],
       [0.64978663, 0.69691305, 0.69132071, 0.97447753, 0.42276086,
        0.54142597, 0.40589066, 0.95258867, 0.19823718, 0.11023176],
       [0.11175206, 0.333044  , 0.46108866, 0.68649247, 0.5558968 ,
        0.25057958, 0.59303769, 0.45446503, 0.69464593, 0.7404538 ],
       [0.86675205, 0.76797992, 0.89944056, 0.08959661, 0.47424144,
        0.27232782, 0.98160603, 0.08884214, 0.14020889, 0.89783734],
       [0.72635928, 0.16478777, 0.3727920

In [18]:
arr1.min()

0.035955481624622365

In [19]:
arr1.max()

0.9816060250001727

In [20]:
arr2 = np.random.random((10))
arr2

array([0.96056199, 0.1029047 , 0.91598829, 0.54840708, 0.29221043,
       0.51055858, 0.41625525, 0.43482985, 0.37930556, 0.18543429])

In [21]:
arr2.mean()

0.4746456017540992

In [22]:
arr3 = np.ones((5,5))
arr3[1:-1, 1:-1] = 0
arr3

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.pad(arr3, pad_width=1, constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [26]:
0 * np.nan

nan

In [27]:
np.nan == np.nan

False

In [28]:
np.inf > np.nan

False

In [29]:
np.nan - np.nan

nan

In [30]:
0.3 == 3 * 0.1

False

In [31]:
mat4 = np.diag(1 + np.arange(4), k = -1)
mat4

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [32]:
mat5 = np.zeros((8, 8), dtype=int)
mat5[1::2, ::2] = 1
mat5[::2, 1::2] = 1
mat5

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [33]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

In [34]:
arr5 = np.array([[0, 1], [1, 0]])
mat6 = np.tile(arr5, (4, 4))
mat6

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [36]:
mat7 = np.random.random((5, 5))
matmax = mat7.max()
matmin = mat7.min()
mat7 = (mat7 - matmin)/(matmax - matmin)
mat7

array([[0.97364863, 0.16557679, 0.17225429, 0.3537275 , 0.2283558 ],
       [0.22649259, 0.22564259, 0.61253169, 1.        , 0.53261331],
       [0.19526962, 0.00335929, 0.24145271, 0.14707852, 0.        ],
       [0.2356393 , 0.70851727, 0.89510426, 0.38256159, 0.91109947],
       [0.24907216, 0.71307374, 0.24201361, 0.73397469, 0.88507873]])

In [37]:
Z= np.dot(np.ones((5,3)), np.ones((3,2)))
Z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [38]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [39]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-39-cd809174da5d>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-39-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

In [40]:
def round_array(x, y):
    return np.round(x, y)
test = np.array([38.16, 0.26, 11.98])
round_array(test, 0)

array([38.,  0., 12.])

In [41]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 4, 9, 8, 10])
np.intersect1d(a, b)

array([2, 4])

In [42]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-42-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [43]:
today = np.datetime64('today', 'D')
today

Today:  2022-04-08


In [45]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
yesterday

numpy.datetime64('2022-04-07')

In [46]:
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
tomorrow

numpy.datetime64('2022-04-09')

In [47]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [49]:
np.linspace(0, 1, 10, endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [51]:
ar1 = np.random.random(10)
ar1.sort()
ar1

array([0.13880872, 0.30369749, 0.30452868, 0.41369635, 0.41758206,
       0.54460829, 0.56292507, 0.57660723, 0.81534285, 0.98669072])

In [3]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
np.array_equal(a, b)

False

In [5]:
c = np.array([1, 2, 3, 4, 5])
c.flags.writeable = False


In [8]:
d = np.random.random((10, 2))
x, y = d[:, 0], d[:, 1]
srt = np.sqrt(x**2 + y**2)
tan = np.arctan2(y, x)
srt
tan

array([1.39973999, 1.12339752, 0.56393502, 0.81997764, 0.78661422,
       0.63103259, 0.97820927, 0.55228229, 1.10317555, 1.31985687])

In [9]:
e = np.array([1, 2, 3, 5, 4, 0])
e[e.argmax()] = 0
e

array([1, 2, 3, 0, 4, 0])

In [10]:
f = np.array([1, 2, 3, 4, 5])
for i in range(len(f)):
    print(f[i])

1
2
3
4
5


In [15]:
g =  np.random.random((10, 2))
x, y = np.atleast_2d(g[:, 0], g[:, 1])
ans = np.sqrt((x-x.T)**2 + (y-y.T)**2)
ans

array([[0.        , 0.72559516, 0.56224155, 0.05314509, 0.6665745 ,
        0.64709754, 0.54994281, 0.8599045 , 0.85377867, 0.48183396],
       [0.72559516, 0.        , 0.21513927, 0.7196338 , 0.86807993,
        0.33189543, 0.48047962, 0.86947445, 1.05468059, 0.75765308],
       [0.56224155, 0.21513927, 0.        , 0.56847568, 0.8690669 ,
        0.41933269, 0.50544397, 0.92853967, 1.06987046, 0.72285644],
       [0.05314509, 0.7196338 , 0.56847568, 0.        , 0.61360333,
        0.61755554, 0.51038037, 0.80884057, 0.80066472, 0.42910623],
       [0.6665745 , 0.86807993, 0.8690669 , 0.61360333, 0.        ,
        0.55340362, 0.38771485, 0.24285947, 0.20499451, 0.18617291],
       [0.64709754, 0.33189543, 0.41933269, 0.61755554, 0.55340362,
        0.        , 0.17696567, 0.53774106, 0.7295041 , 0.47893601],
       [0.54994281, 0.48047962, 0.50544397, 0.51038037, 0.38771485,
        0.17696567, 0.        , 0.42505598, 0.57662002, 0.30214455],
       [0.8599045 , 0.86947445, 0.9285396

In [17]:
h = np.array([1, 2, 3, 4])
np.ndenumerate(h)

In [18]:
i = np.array([1, 2, 3, 4, 5, 6, 7, 8])
val = 9.5
i = np.asarray(i)
idx = (np.abs(i - val)).argmin()
i[idx]

8